version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  install_dependencies:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Lint code

  build_app:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - build_app:
          requires:
            - install_dependencies
